apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: tnechepurencko/my_app:latest
        ports:
        - containerPort: 5000
          protocol: TCP
          name: http
        resources:
          limits:
            cpu: 50m
            memory: 20Mi
          requests:
            cpu: 50m
            memory: 20Mi
        envFrom:
          - configMapRef:
              name: config-map-1
        volumeMounts:
        - name: config-volume
          mountPath: "/config.json"
          subPath: config.json
      volumes:
      - name: config-volume
        configMap:
          name: config-map-1